# docker/docker-compose.yml
# Orquestração dos serviços (web server, bot do Discord, servidor Flask)

version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/agenciamgb/storage
      - ./scripts:/var/www/scripts
      - ./public:/var/www/html
      - ./config:/var/www/config

  bot:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./storage:/var/www/agenciamgb/storage
      - ./scripts:/var/www/scripts
      - ./public:/var/www/html
      - ./config:/var/www/config
    environment:
      - TOKEN=SEU_TOKEN_AQUI
    command: ["python3", "/var/www/scripts/bot.py"]

  flask:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/var/www/agenciamgb/storage
      - ./scripts:/var/www/scripts
      - ./public:/var/www/html
      - ./config:/var/www/config
    command: ["python3", "/var/www/scripts/gs_server.py"]