version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/www/stats/logs
      - ./demos:/var/www/stats/demos
      - ./player_cards:/var/www/stats/player_cards
    environment:
      - DB_PATH=/var/www/stats/stats.db

  bot:
    image: python:3.10-slim
    command: python /app/bot.py
    volumes:
      - ./logs:/var/www/stats/logs
      - ./demos:/var/www/stats/demos
      - ./player_cards:/var/www/stats/player_cards
    environment:
      - TOKEN=SEU_TOKEN_AQUI
      - DB_PATH=/var/www/stats/stats.db
    depends_on:
      - web

  gs_server:
    image: python:3.10-slim
    command: python /app/gs_server.py
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/var/www/stats/logs
      - ./demos:/var/www/stats/demos
      - ./player_cards:/var/www/stats/player_cards
    environment:
      - DB_PATH=/var/www/stats/stats.db
    depends_on:
      - web